### ISSUE TITLE
Tuxphones daemon dies instantly

### ISSUE THREAD

**Issue by CamperSamu** [ImTheSquid/Tuxphones#11]
System info:
- Garuda Linux (Arch)
- Canary 146529 (123495a)
- BetterDiscord 1.6.3
- Host 0.0.139 Linux 64-Bit (5.19.8-Xanmod1-1-X64v2)
- Using PipeWire 0.3.57 with WirePlumber
- systemd 251 (251.4-1-arch)

**Comment by Dreaming-Codes** [comment]
Since audio is still in development Tuxphones isn't ready yet for production and so ./install.sh isn't working. If you want to try Tuxphones anyway you can just simply cd into daemon and run `cargo run`

**Comment by ImTheSquid** [comment]
README has been updated to hopefully prevent this issue from happening again.
