### ISSUE TITLE
Selected ChannelID on Go Live with Sound is null

### ISSUE THREAD

**Issue by CamperSamu** [ImTheSquid/Tuxphones#12]
https://paste.gg/p/anonymous/ce4c7ce43b864f1e8ef95b71e6b83d49

When pressing the Go Live button, tuxphones sources get created but the live fails to start

**Comment by CamperSamu** [comment]
Also opening another live and then closing it after this causes tuxphones to crash:
`2022-09-14T18:27:49.625200Z  INFO tuxphones: [GetInfo] Command processed (applications found: 1)
thread 'tokio-runtime-worker' panicked at 'Failed to send heartbeat: AlreadyClosed', src/discord.rs:223:142`

**Comment by Dreaming-Codes** [comment]
> but the live fails to start

What do you mean? We haven't implemented stream feedback for the user that is streaming so you'll not see anything on the interface that indicate that you're streaming but other users should be able to see your live. I'm saying this because from the logs it looks like the stream has started.

**Comment by Dreaming-Codes** [comment]
@ImTheSquid Can you give the feedback thing a look? Because I remember that at a certain point of the development we got that working. Not the stream preview for the streaming user but at least the streaming UI on the left corner of the screen.

**Comment by ImTheSquid** [comment]
Nothing in Discord changes right now to indicate that you're streaming; we currently have all of that information blocked to make debugging easier. The only thing that works in Discord right now is the stream preview that is shown to everyone else.

**Comment by CamperSamu** [comment]
> What do you mean? We haven't implemented stream feedback for the user that is streaming so you'll not see anything on the interface that indicate that you're streaming but other users should be able to see your live. I'm saying this because from the logs it looks like the stream has started.

Oh my bad, I tested this alone before hopping on a call with my friends.
Will test it with someone later today
