### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ChickenIQ** [ImTheSquid/Tuxphones#16]
Does it/will it work with pipewire?

**Comment by ImTheSquid** [comment]
Currently the goal is to get Tuxphones working with X11 and PulseAudio, but afterwards we're planning on adding support for PipeWire and Wayland.

**Comment by Dreaming-Codes** [comment]
Currently, the deamon is able to capture only audio from pulse's application, so any app if you're using pulse or only pulse legacy app if you're using pipewire.
Since I use pipewire on all my systems, I will surely work on native support for it after getting a working state.

Same for wayland.

**Comment by ChickenIQ** [comment]
> Currently, the deamon is able to capture only audio from pulse's application, so any app if you're using pulse or only pulse legacy app if you're using pipewire.
> Since I use pipewire on all my systems, I will surely work on native support for it after getting a working state.
> 
> Same for wayland.

Thanks.
You should add this to the Readme, but a little more clarified for anyone to read.
