### ISSUE TITLE
Stream doesn't work

### ISSUE THREAD

**Issue by LyXAsuna** [ImTheSquid/Tuxphones#19]
2022-12-07T18:53:43.922505Z  INFO tuxphones: [StartStream] Command received
thread 'tokio-runtime-worker' panicked at 'Failed to initialize gstreamer pipeline: Element(BoolError { message: "Failed to find element factory with name 'ximagesrc' for creating element", filename: "/home/loli/.cargo/registry/src/github.com-1ecc6299db9ec823/gstreamer-0.19.3/src/element_factory.rs", function: "gstreamer::element_factory", line: 254 })', src/lib.rs:136:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-12-07T18:53:43.929318Z ERROR tuxphones: Error removing socket file: No such file or directory (os error 2)

and my game audio fucks up lol

**Comment by ImTheSquid** [comment]
Seems you figured this out on your own, but for anyone else, make sure you're on the latest version (and keep in mind audio does not work as of yet).
