### ISSUE TITLE
Whats the Status?

### ISSUE THREAD

**Issue by yofukashino** [ImTheSquid/Tuxphones#22]
Whats the status on this project right now? I would love to help and get this working if possible. So just want to know if this is even maintained anymore since last issue was in start of 2023.

**Comment by ImTheSquid** [comment]
I've kinda gotten too busy to actively work on this, and I don't daily drive Linux at the current moment. I would be open to helping out by telling you what I know though!

**Comment by Dreaming-Codes** [comment]
Same for me, I'm now using vesktop which has audio sharing

**Comment by yofukashino** [comment]
I just need push to talk so I want some way to get this working on native client. i can deal with discord's plugin side, wouldn't be using better discord anyways

just help me get this working as a server maybe?

**Comment by yofukashino** [comment]
also, can you explain to me how this works? so that I may even have an easier time working on this? from plugin side but still

some discord server or something to chat about this more easily?

**Comment by ImTheSquid** [comment]
The original idea is we had a BetterDiscord plugin that would intercept requests to share your screen during a call, and forwards that call to a daemon that handles all of the WebRTC stuff itself. For some reason it was pretty much impossible to get everything working together in a way that worked, and we always had strange issues.

**Comment by yofukashino** [comment]
what klind of issues to be precise. daemon side or discord client side?

**Comment by yofukashino** [comment]
i recreated the plugin and got the daemon working. in console, it says the stream started but it doesn't start. any tips?

**Comment by ImTheSquid** [comment]
This is basically where we stopped. You will have to experiment on your own from here on.

**Comment by Dreaming-Codes** [comment]
Yeah, I remember that at a certain point we got video working

**Comment by yofukashino** [comment]
yeah i am unable to get even video working for now

**Comment by bryandesrosiers** [comment]
Any updates on your try at this @yofukashino ?

**Comment by yofukashino** [comment]
> Any updates on your try at this @yofukashino ?

i don't wanna mess with rust so I cant do anything.
